from enum import Enum


class ApplicationErrorCode(Enum):
    STORE_PHOTO_ERROR = "STORE_PHOTO_ERROR"
    IMPORT_MEASUREMENTS_ERROR = "IMPORT_MEASUREMENTS_ERROR"
    NOT_SUPPORTED_METRIC_ERROR = "NOT_SUPPORTED_METRIC_ERROR"
