"""Add name column to areas_of_interest

Revision ID: 35ca0742c359
Revises: e81e4a6ce665
Create Date: 2025-10-13 18:41:25.814181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35ca0742c359'
down_revision: Union[str, Sequence[str], None] = 'e81e4a6ce665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas_of_interest', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('areas_of_interest', 'name')
    # ### end Alembic commands ###
