"""Add table uploaded_photos

Revision ID: 7757b4f0be5b
Revises: 35ca0742c359
Create Date: 2025-10-16 02:26:18.615024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7757b4f0be5b'
down_revision: Union[str, Sequence[str], None] = '35ca0742c359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('photo_full_path', sa.String(), nullable=False),
    sa.Column('photo_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas_of_interest.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploaded_photos')
    # ### end Alembic commands ###
