"""Create areas_of_interest table

Revision ID: e81e4a6ce665
Revises: 
Create Date: 2025-10-09 02:43:58.837686

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e81e4a6ce665'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas_of_interest',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2,
                                                                     from_text='ST_GeomFromEWKT', name='geometry'),
                              nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='public'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('areas_of_interest', schema='public')
    # ### end Alembic commands ###
